/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TFI_1035ListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_TFI_1035ListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZC_TFI_1035ListGenerated.onFilterBar().iCheckFilterField("Company Code");
            Then.onTheZC_TFI_1035ListGenerated.onFilterBar().iCheckFilterField("Cost Center Category");
            Then.onTheZC_TFI_1035ListGenerated.onFilterBar().iCheckFilterField("Material Group");
            Then.onTheZC_TFI_1035ListGenerated.onFilterBar().iCheckFilterField("Original Account");
            Then.onTheZC_TFI_1035ListGenerated.onFilterBar().iCheckFilterField("Target Account");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZC_TFI_1035ListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZC_TFI_1035ListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZC_TFI_1035ListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_TFI_1035ListGenerated.onTable().iCheckColumns(undefined, {"CompanyCode":{"header":"Company Code"},"CostCenterCategory":{"header":"Cost Center Category"},"MaterialGroup":{"header":"Material Group"},"OriginalAccount":{"header":"Original Account"},"TargetAccount":{"header":"Target Account"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZC_TFI_1035ListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheZC_TFI_1035ListGenerated.onTable().iCheckRows();

            When.onTheZC_TFI_1035ListGenerated.onTable().iPressRow(0);
            Then.onTheZC_TFI_1035ObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});