/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TFI_1035ObjectPageObjectPage journey");

        opaTest("Navigate to ZC_TFI_1035ObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZC_TFI_1035ListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheZC_TFI_1035ListGenerated.onTable().iCheckRows();
            When.onTheZC_TFI_1035ListGenerated.onTable().iPressRow(0);

            Then.onTheZC_TFI_1035ObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_TFI_1035ObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CompanyCode" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CostCenterCategory" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "MaterialGroup" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "OriginalAccount" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "TargetAccount" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedBy" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedAt" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChangedBy" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChangedAt" });
            Then.onTheZC_TFI_1035ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LocalLastChangedAt" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});