/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TSD_1023ListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_TSD_1023ListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Sales Organization");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Plant");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Customer");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Customer");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Sales Document Type");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Yy1SalesdoctypeSdh");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Rate");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Created By");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Created On");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Changed By");
            Then.onTheZC_TSD_1023ListGenerated.onFilterBar().iCheckFilterField("Changed On");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZC_TSD_1023ListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZC_TSD_1023ListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZC_TSD_1023ListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_TSD_1023ListGenerated.onTable().iCheckColumns(undefined, {"SalesOrganization":{"header":"Sales Organization"},"Plant":{"header":"Plant"},"SoldToParty":{"header":"Customer"},"ShipToParty":{"header":"Customer"},"SalesDocumentType":{"header":"Sales Document Type"},"Yy1SalesdoctypeSdh":{"header":"Yy1SalesdoctypeSdh"},"Rate":{"header":"Rate"},"CreatedBy":{"header":"Created By"},"CreatedAt":{"header":"Created On"},"LastChangedBy":{"header":"Changed By"},"LastChangedAt":{"header":"Changed On"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZC_TSD_1023ListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheZC_TSD_1023ListGenerated.onTable().iCheckRows();

            When.onTheZC_TSD_1023ListGenerated.onTable().iPressRow(0);
            Then.onTheZC_TSD_1023ObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});