/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TSD_1023ObjectPageObjectPage journey");

        opaTest("Navigate to ZC_TSD_1023ObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_TSD_1023ListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_TSD_1023ListGenerated.onTable().iCheckRows();
            When.onTheZC_TSD_1023ListGenerated.onTable().iPressRow(0);

            Then.onTheZC_TSD_1023ObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_TSD_1023ObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SalesOrganization" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Plant" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SoldToParty" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ShipToParty" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SalesDocumentType" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Yy1SalesdoctypeSdh" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Rate" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedBy" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedAt" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChangedBy" });
            Then.onTheZC_TSD_1023ObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChangedAt" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});