/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CustomerReportObjectPageObjectPage journey");

        opaTest("Navigate to CustomerReportObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheCustomerReportList.onFilterBar().iExecuteSearch();

            Then.onTheCustomerReportList.onTable().iCheckRows();
            When.onTheCustomerReportList.onTable().iPressRow(0);

            Then.onTheCustomerReportObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheCustomerReportObjectPage.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Customer" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CompanyCode" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SalesOrganization" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DistributionChannel" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Division" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CustomerName" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreationDate" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SalesOffice" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SalesGroup" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SalesGroupDescription" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Currency" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ShippingCondition" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SearchTerm1" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SearchTerm2" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Street" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "HouseNumber" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Street2" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Street3" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Street4" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Street5" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PostalCode" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "City" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Country" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AddressTimeZone" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CustomerPaymentTerms" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PaymentTermsDescription" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SupplyingPlant" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Remark" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ContactPerson" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Telephone" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Fax" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DeletionIndicatorAllScope" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DeletionIndicatorCompany" });
            Then.onTheCustomerReportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DeletionIndicatorAllSalesArea" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});