/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CustomerReportListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheCustomerReportList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheCustomerReportList.onFilterBar().iCheckFilterField("Customer");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheCustomerReportList.onTable().iCheckColumns(undefined, {"Customer":{"header":"Customer"},"CompanyCode":{"header":"Company Code"},"SalesOrganization":{"header":"Sales Organization"},"DistributionChannel":{"header":"Distribution Channel"},"Division":{"header":"Division"},"CustomerName":{"header":"CustomerName"},"CreationDate":{"header":"Created On"},"SalesOffice":{"header":"Sales Office"},"SalesGroup":{"header":"Sales Group"},"SalesGroupDescription":{"header":"Sales Group Description"},"Currency":{"header":"Currency"},"ShippingCondition":{"header":"Shipping Conditions"},"SearchTerm1":{"header":"Search Term 1"},"SearchTerm2":{"header":"Search Term 2"},"Street":{"header":"Street"},"HouseNumber":{"header":"House Number"},"Street2":{"header":"Street 2"},"Street3":{"header":"Street 3"},"Street4":{"header":"Street 4"},"Street5":{"header":"Street 5"},"PostalCode":{"header":"Postal Code"},"City":{"header":"City"},"Country":{"header":"Country/Region Key"},"AddressTimeZone":{"header":"Time Zone"},"CustomerPaymentTerms":{"header":"Terms of Payment"},"PaymentTermsDescription":{"header":"Description"},"SupplyingPlant":{"header":"Delivering Plant"},"Remark":{"header":"Notes"},"ContactPerson":{"header":"ContactPerson"},"Telephone":{"header":"Telephone"},"Fax":{"header":"Fax"},"DeletionIndicatorAllScope":{"header":"Deletion Flag"},"DeletionIndicatorCompany":{"header":"Co.Cde Deletion Flag"},"DeletionIndicatorAllSalesArea":{"header":"Deletion Flag"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheCustomerReportList.onFilterBar().iExecuteSearch();
            
            Then.onTheCustomerReportList.onTable().iCheckRows();

            When.onTheCustomerReportList.onTable().iPressRow(0);
            Then.onTheCustomerReportObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});